import 'package:intl/intl.dart';

List<String> bloodTypes = [
  'A+',
  'A-',
  'B+',
  'B-',
  'AB+',
  'AB-',
  'O+',
  'O-',
];

List<String> municipalities = [
  'Anilao',
  'Atlag',
  'Babatnin',
  'Bagna',
  'Bagong bayan',
  'Balayong',
  'Balite',
  'Bangkal',
  'Barihan',
  'Bulihan',
  'Bungahan',
  'Caingin',
  'Calero',
  'Caliligawan',
  'Canalate',
  'Caniogan',
  'Cofradia',
  'Catmon',
  'Dakila',
  'Guinhawa',
  'Liang',
  'Ligas',
  'Longos',
  'Lugam',
  'Look 1st',
  'Look 2nd',
  'Mabolo',
  'Mambog',
  'Masile',
  'Matimbo',
  'Mojon',
  'Namayan',
  'Niugan',
  'Pamarawan',
  'Panasahan',
  'Pinagbakahan',
  'San agustin',
  'San gabriel',
  'San juan',
  'San pablo',
  'Santiago',
  'Santor',
  'San vicente',
  'Santisima trinidad',
  'Santo cristo',
  'Santo rosario',
  'Santo niño',
  'Sumapang bata',
  'Sumapang matanda',
  'Taal',
  'Tikay',
];

final datetimeFormatter = new DateFormat('MMMM dd, yyyy hh:mm a');

final dateFormatter = new DateFormat('MMMM dd, yyyy');